FROM node:20

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .

# Expose Vite's default port
EXPOSE 3001

# Use Vite's development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
