FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port
EXPOSE 3000

# Start the development server with host binding to make it accessible outside the container
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
