# Generated by Django 4.1.7 on 2024-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_tier_features_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
