# Generated by Django 4.1.7 on 2024-12-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_product_default_trial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("percentage", models.PositiveIntegerField(blank=True, null=True)),
                ("money", models.PositiveIntegerField(blank=True, null=True)),
                ("trial_days", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Discount Code",
                "verbose_name_plural": "Discount Codes",
                "db_table": "discount_codes",
            },
        ),
    ]
