# Generated by Django 4.1.7 on 2025-01-13 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_code_product_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discountcode",
            old_name="money",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="discountcode",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discountcode",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percent_off", "Percentage Off"),
                    ("amount_off", "Fixed Amount Off"),
                ],
                default="percent_off",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="duration",
            field=models.CharField(
                choices=[
                    ("forever", "Forever"),
                    ("once", "Once"),
                    ("repeating", "Repeating"),
                ],
                default="once",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="duration_in_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="stripe_coupon_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
