# Generated by Django 4.1.7 on 2025-01-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_code_matches_stripe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="next_billing_date",
        ),
    ]
