# Generated by Django 4.1.7 on 2025-01-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_remove_subscription_billingdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("incomplete", "Incomplete"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
