# Generated by Django 4.1.7 on 2025-01-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0012_remove_subscription__is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="billing_cycle",
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
