# Generated by Django 4.1.7 on 2024-10-07 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_onetimepassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimepassword",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
