# Generated by Django 5.1.7 on 2025-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_user_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
