# Generated by Django 5.1.15 on 2026-01-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_nullable_payment_method"),
        ("league", "0003_trade_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_team",
            field=models.ForeignKey(
                blank=True,
                help_text="User's last selected team",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="league.team",
            ),
        ),
    ]
