# Generated by Django 4.1.7 on 2024-12-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0001_payment_tables"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tier",
            old_name="stripe_price_id",
            new_name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="tier",
            name="price_lifetime",
        ),
        migrations.RemoveField(
            model_name="tier",
            name="price_monthly",
        ),
        migrations.RemoveField(
            model_name="tier",
            name="price_yearly",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("user", "tier")},
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("lifetime", "Lifetime"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("stripe_price_id", models.CharField(max_length=255)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payment.tier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Cycle",
                "verbose_name_plural": "Payment Cycles",
                "db_table": "payment_cycles",
                "unique_together": {("tier", "billing_cycle")},
            },
        ),
    ]
