# Generated by Django 4.1.7 on 2024-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_rename_stripe_price_id_tier_stripe_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="features",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
