# Generated by Django 4.1.7 on 2024-12-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_product_tier_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tier",
            options={
                "ordering": ["order"],
                "verbose_name": "Tier",
                "verbose_name_plural": "Tiers",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="default_trial_days",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
