# Generated by Django 4.1.7 on 2024-12-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_discount_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.product",
            ),
        ),
    ]
