# Generated by Django 4.1.7 on 2025-01-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_add_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.price",
            ),
        ),
    ]
