# Generated by Django 4.1.7 on 2025-01-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_subscription_fk_to_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
    ]
