# Generated by Django 5.1.7 on 2025-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0013_subscription_remove_billing_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
